name: clone_carrot_market         # 앱 이름
description: "clone_carrot_market"  # 앱 설명

publish_to: 'none'                # pub.dev에 공개하지 않음

version: 1.0.0+1                  # 버전명+빌드번호

environment:                     # 사용하는 Dart SDK 버전
  sdk: ^3.5.2

dependencies:                    # 앱 실행에 필요한 패키지 목록
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8        # 예: iOS 스타일 아이콘
  flutter_svg: ^2.0.7
  
dev_dependencies:                # 개발/테스트용 패키지
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0          # 코드 검사 기준

flutter:                         # Flutter 관련 설정
  uses-material-design: true     # 머티리얼 아이콘 사용

  assets:                        # 앱에 포함할 리소스 (이미지, 폰트 등)
    - assets/                    # 폴더나 개별 파일 경로 등록 가능
    - assets/icons/logo.svg


# (fonts: 섹션은 주석 처리되어 있지만 필요 시 활성화 가능)
